from tools.patch_tool import extract_patch, apply_patch
from tools.test_runner_tool import run_tests
import os


def validate_patch(repo_path, fix_result):

    patch_text = fix_result.get("patch")

    # safety check
    if not patch_text:
        return {
            "status": "failed",
            "message": "No patch generated by Fix Generator"
        }

    patch_lines = extract_patch(patch_text)

    print("\nPATCH LINES:\n")
    print(patch_lines)

    file_path = os.path.join(repo_path, "views.py")

    apply_patch(file_path, patch_lines)

    print("\nPatch applied to:", file_path)

    test_result = run_tests(repo_path)

    if test_result["return_code"] == 0:
        return {
            "status": "success",
            "message": "Patch fixed the issue"
        }

    return {
        "status": "failed",
        "message": "Tests failed"
    }